server:
  port: 8000
spring:
  cloud:
    gateway:
      routes:
      - id: order-service-route
        uri: lb:http://order-service
        predicates:
        - Path=/orders-service/api/**
        - After=2022-11-02T13:37:09+08:00[Asia/Shanghai]
        filters:
        - RewritePath=/orders-service/api/(?<segment>.*), /orders/$\{segment}
